'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, BarChart3, Brain, RefreshCw } from 'lucide-react'
export default function IntelligencePage(){
 const [data,setData]=useState<any>(null); const [status,setStatus]=useState('Cargando…')
 async function load(){setStatus('Sincronizando…'); const r=await fetch('/api/intelligence/overview',{cache:'no-store'}); const d=await r.json(); if(!r.ok){setStatus(d.error||'Error');return}setData(d);setStatus('Actualizado')}
 useEffect(()=>{void load()},[])
 const m=data?.metrics||{}
 return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/business-os" className="inline-flex items-center gap-2 text-sm font-black text-primary"><ArrowLeft className="size-4"/>Business OS</Link><section className="mt-5 rounded-[2rem] border border-border bg-card p-7 sm:p-10"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-primary"><Brain className="size-3.5"/>Credi Intelligence</div><h1 className="mt-4 text-3xl font-black sm:text-5xl">Inteligencia empresarial</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Indicadores del negocio construidos con datos reales de operaciones. Los campos sin evidencia suficiente se muestran como no disponibles en lugar de inventarse.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-border bg-background px-4 py-3 text-sm font-black"><RefreshCw className="size-4"/>Actualizar</button></div></section><section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['GMV',m.gmv],['Revenue',m.revenue],['Pedidos',m.orders],['AOV',m.aov],['Recompra',m.repeat_purchase_rate==null?'N/D':`${Math.round(m.repeat_purchase_rate*100)}%`],['Inventario',m.inventory_turnover==null?'N/D':m.inventory_turnover],['B2B pipeline',m.b2b_pipeline],['AI-assisted revenue',m.ai_assisted_revenue]].map(([k,v])=><article key={String(k)} className="rounded-2xl border border-border bg-card p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-muted-foreground">{k}</p><p className="mt-2 text-3xl font-black">{typeof v==='number'?v.toLocaleString('es-ES',{maximumFractionDigits:2}):v}</p></article>)}</section><section className="mt-6 rounded-3xl border border-border bg-card p-6"><div className="flex items-center gap-3"><BarChart3 className="size-5 text-primary"/><h2 className="text-xl font-black">Calidad de datos</h2><span className="ml-auto text-xs font-bold text-muted-foreground">{status}</span></div><div className="mt-5 grid gap-3 md:grid-cols-2">{Object.entries(data?.data_quality||{}).map(([k,v])=><div key={k} className="rounded-2xl bg-muted/30 p-4"><p className="text-xs font-black">{k}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{String(v)}</p></div>)}</div></section></div></main>
}