import type { Metadata } from 'next'
import Link from 'next/link'
import { redirect } from 'next/navigation'
import type { ReactNode } from 'react'
import { Bot, Boxes, Building2, ChartNoAxesCombined, MessageSquareText, PackageSearch, ReceiptText, ShieldCheck, Sparkles, Workflow, ArrowUpRight, BarChart3, Scale, WalletCards, UsersRound } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'

export const metadata: Metadata={title:'Credi Business OS | Credi Marketplace',description:'Centro operativo inteligente para ventas, compras, inventario, B2B, IA, reputación y automatización.',robots:{index:false,follow:false}}
export const dynamic='force-dynamic'
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <article className="rounded-3xl border border-border bg-card p-5 shadow-sm"><p className="text-[11px] font-black uppercase tracking-[.17em] text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-black tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{hint}</p></article>}
function Module({href,icon,eyebrow,title,text,action}:{href:string;icon:ReactNode;eyebrow:string;title:string;text:string;action:string}){return <Link href={href} className="group rounded-3xl border border-border bg-card p-6 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-md"><div className="flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">{icon}</div><p className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-primary">{eyebrow}</p><h2 className="mt-1 text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p><span className="mt-5 inline-flex text-sm font-black text-primary group-hover:underline">{action} →</span></Link>}
export default async function BusinessOsPage(){
 const supabase=await createClient();const {data:auth,error}=await supabase.auth.getUser();if(error||!auth.user)redirect('/login?next=%2Fbusiness-os');const user=auth.user
 const {data:store}=await supabase.from('stores').select('id,store_name,is_verified,is_active').eq('vendor_id',user.id).maybeSingle();const since=new Date(Date.now()-90*86400000).toISOString()
 const [{data:products},{count:rfqCount},{count:automationCount},{count:auditCount},{data:orderItems}]=await Promise.all([
  supabase.from('products').select('id,title,price,stock,is_active').eq('store_id',store?.id??'').order('created_at',{ascending:false}).limit(200),
  supabase.from('business_rfqs').select('id',{count:'exact',head:true}).eq('buyer_id',user.id),
  supabase.from('business_automation_rules').select('id',{count:'exact',head:true}).eq('owner_id',user.id).eq('enabled',true),
  supabase.from('agent_action_audit').select('id',{count:'exact',head:true}).eq('owner_id',user.id),
  store?.id?supabase.from('order_items').select('order_id,product_id,quantity,subtotal').eq('store_id',store.id).gte('created_at',since).limit(10000):Promise.resolve({data:[] as any[]}),
 ])
 const items=products??[];const active=items.filter(x=>x.is_active).length;const stock=items.reduce((s,x)=>s+Math.max(0,Number(x.stock)),0);const lowStock=items.filter(x=>Number(x.stock)>0&&Number(x.stock)<=5).length;const company=store?.store_name||user.email?.split('@')[0]||'Mi empresa'
 const uniqueOrderIds=[...new Set((orderItems??[]).map(x=>x.order_id))];const {data:orders}=uniqueOrderIds.length?await supabase.from('orders').select('id,buyer_id,status,total_amount').in('id',uniqueOrderIds).limit(10000):{data:[] as any[]};const completed=(orders??[]).filter(x=>['paid','processing','shipped','delivered'].includes(String(x.status).toLowerCase()));const revenue=(orderItems??[]).filter(x=>completed.some(o=>o.id===x.order_id)).reduce((s,x)=>s+Number(x.subtotal||0),0);const buyerMap=new Map<string,number>();for(const o of completed)buyerMap.set(o.buyer_id,(buyerMap.get(o.buyer_id)??0)+1);const repeat=buyerMap.size?[...buyerMap.values()].filter(v=>v>1).length/buyerMap.size:null;const aov=completed.length?revenue/completed.length:0
 return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto w-full max-w-[1560px] px-4 py-6 sm:px-6 lg:px-8 lg:py-10"><section className="relative overflow-hidden rounded-[2rem] border border-border bg-card p-6 shadow-sm sm:p-8 lg:p-10"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-transparent"/><div className="relative flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-4xl"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-primary"><Sparkles className="size-3.5"/> Credi Business OS</span><span className={`rounded-full px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] ${store?.is_verified?'bg-emerald-500/10 text-emerald-700':'bg-amber-500/10 text-amber-700'}`}>{store?.is_verified?'Empresa verificada':'Completa verificación'}</span></div><h1 className="mt-5 text-3xl font-black tracking-tight sm:text-5xl lg:text-6xl">{company}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground sm:text-base">Una sola consola para vender, comprar, abastecerte, controlar inventario, conversar con clientes y proveedores, automatizar operaciones y trabajar con agentes de IA.</p></div><div className="flex flex-wrap gap-2"><Link href="/commerce-studio" className="inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground">Commerce Studio <ArrowUpRight className="size-4"/></Link><Link href="/products/create" className="rounded-2xl border border-border bg-background px-5 py-3 text-sm font-black">Crear oferta</Link><Link href="/abastecimiento" className="rounded-2xl border border-border bg-background px-5 py-3 text-sm font-black">Nueva solicitud B2B</Link><Link href="/chat" className="rounded-2xl border border-border bg-background px-5 py-3 text-sm font-black">Credi Chat</Link></div></div></section>
 <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Ofertas" value={items.length.toLocaleString('es-ES')} hint="Activos comerciales"/><Metric label="Activos" value={active.toLocaleString('es-ES')} hint="Listos para operar"/><Metric label="Stock" value={stock.toLocaleString('es-ES')} hint="Unidades disponibles"/><Metric label="RFQ B2B" value={Number(rfqCount??0).toLocaleString('es-ES')} hint="Solicitudes propias"/><Metric label="Automaciones" value={Number(automationCount??0).toLocaleString('es-ES')} hint="Reglas activas"/></section>
 <section className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Revenue 90d" value={revenue.toLocaleString('en-US',{maximumFractionDigits:2})} hint="Ventas completadas"/><Metric label="Pedidos" value={completed.length.toLocaleString('es-ES')} hint="Últimos 90 días"/><Metric label="AOV" value={aov.toLocaleString('en-US',{maximumFractionDigits:2})} hint="Ticket medio"/><Metric label="Recompra" value={repeat===null?'—':`${(repeat*100).toFixed(1)}%`} hint="Proxy 90d"/><Metric label="Compradores" value={buyerMap.size.toLocaleString('es-ES')} hint="Cohorte observada"/><Metric label="Agente" value={Number(auditCount??0).toLocaleString('es-ES')} hint="Acciones auditadas"/></section>
 {lowStock>0?<section className="mt-6 rounded-3xl border border-amber-300/40 bg-amber-50 p-5 text-amber-950 sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-amber-700">Inventario inteligente</p><h2 className="mt-1 text-xl font-black">{lowStock} referencias necesitan atención</h2><p className="mt-1 text-sm text-amber-900/80">Revisa existencias, previsiones y reposición antes de perder una venta.</p></div><Link href="/inventario" className="rounded-xl bg-amber-950 px-4 py-3 text-sm font-black text-amber-50">Abrir inventario</Link></div></section>:null}
 <section className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Module href="/abastecimiento" icon={<PackageSearch className="size-6"/>} eyebrow="Procurement" title="Abastecimiento B2B" text="Crea solicitudes de compra, estructura necesidades y prepara procesos de cotización con proveedores." action="Gestionar abastecimiento"/><Module href="/inventario" icon={<Boxes className="size-6"/>} eyebrow="Inventory OS" title="Inventario" text="Controla disponibilidad, reservas, productos críticos y previsiones de reposición." action="Abrir inventario"/><Module href="/intelligence" icon={<BarChart3 className="size-6"/>} eyebrow="Credi Intelligence" title="Intelligence" text="GMV, revenue, AOV, recompra, conversión observada, margen cuando existe costeo y pipeline B2B." action="Analizar negocio"/><Module href="/chat" icon={<MessageSquareText className="size-6"/>} eyebrow="Business Messaging" title="Credi Chat" text="Convierte conversaciones en relaciones comerciales con producto, contexto y operaciones vinculadas." action="Abrir conversaciones"/><Module href="/negociaciones" icon={<Scale className="size-6"/>} eyebrow="Negotiation Engine" title="Negociaciones" text="Gestiona ofertas, límites, rondas y propuestas asistidas por IA." action="Gestionar negociaciones"/><Module href="/wallet" icon={<WalletCards className="size-6"/>} eyebrow="Finance" title="Wallet y pagos" text="Consulta saldo, movimientos y orquesta intents de pago con trazabilidad." action="Abrir finanzas"/><Module href="/proveedores-verificados" icon={<ShieldCheck className="size-6"/>} eyebrow="Trust" title="Proveedores verificados" text="Descubre empresas y ofertas con señales de confianza para reducir fricción comercial." action="Explorar proveedores"/><Module href="/developer" icon={<Building2 className="size-6"/>} eyebrow="Platform" title="Developer + Agentic" text="API, SDK, OAuth PKCE, identidad de agentes, webhooks y catálogo estructurado." action="Abrir plataforma"/></section>
 <section className="mt-8 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-3xl border border-border bg-card p-6 shadow-sm sm:p-7"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-violet-500/10 text-violet-700"><Workflow className="size-5"/></span><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-violet-700">Automations + Agents</p><h2 className="text-xl font-black">De tablero a operación autónoma</h2></div></div><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">La IA observa datos del negocio, propone acciones, solicita autorización cuando corresponde, ejecuta tareas permitidas y deja una huella auditable.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-muted/30 p-4"><p className="text-sm font-black">Observa</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Ventas, inventario, pedidos, proveedores y conversaciones.</p></div><div className="rounded-2xl border border-border bg-muted/30 p-4"><p className="text-sm font-black">Propone</p><p className="mt-1 text-xs leading-5 text-muted-foreground">RFQ, reposición, seguimiento, precio y campañas.</p></div><div className="rounded-2xl border border-border bg-muted/30 p-4"><p className="text-sm font-black">Ejecuta</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Solo acciones autorizadas, registradas y verificables.</p></div></div></div><div className="rounded-3xl border border-border bg-card p-6 shadow-sm sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.18em] text-primary">Business Graph</p><h2 className="mt-1 text-xl font-black">Una inteligencia comercial</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Producto, inventario, clientes, proveedores, pedidos, pagos, conversaciones y reputación comienzan a operar como un mismo contexto.</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-muted/40 p-4"><UsersRound className="size-4 text-primary"/><p className="mt-2 text-xs font-bold text-muted-foreground">Compradores observados</p><p className="mt-1 text-2xl font-black">{buyerMap.size}</p></div><div className="rounded-2xl bg-muted/40 p-4"><ChartNoAxesCombined className="size-4 text-primary"/><p className="mt-2 text-xs font-bold text-muted-foreground">Revenue 90d</p><p className="mt-1 text-2xl font-black">{revenue.toLocaleString('en-US',{maximumFractionDigits:0})}</p></div></div></div></section>
 </div></main>
}
