'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Boxes, Search } from 'lucide-react'
type Json=Record<string,unknown>
const asObject=(value:unknown):Json=>value&&typeof value==='object'&&!Array.isArray(value)?value as Json:{}
export default function ProductGraphPage(){
 const [id,setId]=useState(''); const [data,setData]=useState<Json|null>(null); const [status,setStatus]=useState('')
 async function load(){if(!id.trim())return setStatus('Indica el ID de un producto.');setStatus('Cargando grafo…');const r=await fetch(`/api/product-graph/${encodeURIComponent(id.trim())}`,{cache:'no-store'});const raw:unknown=await r.json();const d=asObject(raw);if(!r.ok){setStatus(typeof d.error==='string'?d.error:'No fue posible cargar el grafo.');return}setData(d);setStatus('Grafo actualizado')}
 useEffect(()=>{const saved=new URLSearchParams(location.search).get('id');if(saved){setId(saved)}},[])
 const product=asObject(data?.product); const commerce=asObject(data?.commerce); const b2b=asObject(data?.b2b_offer); const conversations=Array.isArray(data?.conversations)?data.conversations:[]; const graphLinks=Array.isArray(data?.graph_links)?data.graph_links.filter((x):x is string=>typeof x==='string'):[]
 return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><Link href="/business-os" className="inline-flex items-center gap-2 text-sm font-black text-primary"><ArrowLeft className="size-4"/>Business OS</Link><section className="mt-5 rounded-[2rem] border border-border bg-card p-7 sm:p-10"><div className="flex items-center gap-4"><div className="flex size-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Boxes className="size-7"/></div><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-primary">Credi Product Graph</p><h1 className="text-3xl font-black sm:text-5xl">Activo comercial conectado</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Producto, proveedor, inventario, B2B, reputación, pedidos, conversaciones y publicaciones desde una única representación consultable.</p></div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><input value={id} onChange={e=>setId(e.target.value)} className="flex-1 rounded-xl border border-border bg-background px-4 py-3 text-sm" placeholder="UUID del producto"/><button onClick={load} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground"><Search className="size-4"/>Consultar</button></div>{status&&<p className="mt-3 text-xs text-muted-foreground">{status}</p>}</section>{data&&<><section className="mt-6 grid gap-4 md:grid-cols-3">{[['Producto',product.title],['Precio',product.price],['Stock',product.stock],['B2B',data.b2b_offer?'Configurado':'No configurado'],['Ventas observadas',commerce.quantity_sold_observed],['Conversaciones',conversations.length]].map(([k,v])=><article key={String(k)} className="rounded-2xl border border-border bg-card p-5"><p className="text-[10px] font-black uppercase tracking-[.17em] text-muted-foreground">{String(k)}</p><p className="mt-2 text-2xl font-black">{String(v??'—')}</p></article>)}</section><section className="mt-6 rounded-3xl border border-border bg-card p-6"><h2 className="text-xl font-black">Enlaces del grafo</h2><div className="mt-4 flex flex-wrap gap-2">{graphLinks.map((x)=><span key={x} className="rounded-full bg-primary/10 px-3 py-1.5 text-xs font-black text-primary">{x}</span>)}</div><p className="mt-4 text-xs text-muted-foreground">{b2b ? 'La oferta B2B está disponible en el contexto del grafo.' : 'No existe configuración B2B para este producto.'}</p></section></>}</div></main>
}