import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { retrieveMarketplaceAccount } from '@/lib/payments/stripe-connect'
import { distributedRateLimit } from '@/lib/security/rate-limit'
import { getRequestIp } from '@/lib/security/auth'
export const runtime='nodejs'
export const dynamic='force-dynamic'
export async function GET(request:Request){
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'UNAUTHORIZED'},{status:401})
 const limit=await distributedRateLimit(supabase,`stripe-connect-status:${user.id}:${getRequestIp(request)}`,{limit:30,windowMs:60_000});if(!limit.success)return NextResponse.json({error:'RATE_LIMITED'},{status:429})
 const admin=createAdminClient();const {data:store,error}=await admin.from('stores').select('id,stripe_connect_account_id,stripe_connect_status').eq('vendor_id',user.id).maybeSingle();if(error)return NextResponse.json({error:'STORE_LOOKUP_FAILED'},{status:500});if(!store?.stripe_connect_account_id)return NextResponse.json({ok:true,connected:false,status:'not_started'})
 try{const account=await retrieveMarketplaceAccount(store.stripe_connect_account_id);const requirements=account.requirements&&typeof account.requirements==='object'?account.requirements as Record<string,unknown>:{};const currentlyDue=Array.isArray(requirements.currently_due)?requirements.currently_due:[];const pastDue=Array.isArray(requirements.past_due)?requirements.past_due:[];const config=account.configuration&&typeof account.configuration==='object'?account.configuration as Record<string,unknown>:{};const recipient=config.recipient&&typeof config.recipient==='object'?config.recipient as Record<string,unknown>:null;const capabilities=recipient?.capabilities&&typeof recipient.capabilities==='object'?recipient.capabilities as Record<string,unknown>:null;const balance=capabilities?.stripe_balance&&typeof capabilities.stripe_balance==='object'?capabilities.stripe_balance as Record<string,unknown>:null;const transfers=balance?.stripe_transfers&&typeof balance.stripe_transfers==='object'?balance.stripe_transfers as Record<string,unknown>:null;const transferStatus=typeof transfers?.status==='string'?transfers.status:null;const status=transferStatus==='active'&&currentlyDue.length===0&&pastDue.length===0?'connected':'pending';if(status!==store.stripe_connect_status)await admin.from('stores').update({stripe_connect_status:status,updated_at:new Date().toISOString()}).eq('id',store.id);return NextResponse.json({ok:true,connected:true,account_id:store.stripe_connect_account_id,status,account})}catch(error){console.error('stripe connect status',error);return NextResponse.json({error:'STRIPE_CONNECT_STATUS_FAILED'},{status:502})}
}
