create table if not exists public.chat_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'offline' check (status in ('online','away','offline','busy')),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_calls (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  initiated_by uuid not null references auth.users(id) on delete cascade,
  call_type text not null check (call_type in ('audio','video')),
  status text not null default 'ringing' check (status in ('ringing','connecting','active','ended','declined','missed','failed')),
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_call_participants (
  call_id uuid not null references public.chat_calls(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'participant' check (role in ('initiator','participant')),
  state text not null default 'invited' check (state in ('invited','ringing','accepted','declined','left','connected')),
  joined_at timestamptz,
  left_at timestamptz,
  last_seen_at timestamptz not null default now(),
  primary key (call_id,user_id)
);

create table if not exists public.chat_call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.chat_calls(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  signal_type text not null check (signal_type in ('offer','answer','ice','renegotiate','hangup','mute','camera','screen')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_chat_calls_conversation_created on public.chat_calls(conversation_id, created_at desc);
create index if not exists idx_chat_call_participants_user on public.chat_call_participants(user_id, call_id);
create index if not exists idx_chat_call_signals_recipient on public.chat_call_signals(call_id, recipient_id, id);
create index if not exists idx_chat_presence_updated on public.chat_presence(updated_at desc);

alter table public.chat_presence enable row level security;
alter table public.chat_calls enable row level security;
alter table public.chat_call_participants enable row level security;
alter table public.chat_call_signals enable row level security;

drop policy if exists chat_presence_select on public.chat_presence;
create policy chat_presence_select on public.chat_presence for select to authenticated using (true);
drop policy if exists chat_presence_insert_own on public.chat_presence;
create policy chat_presence_insert_own on public.chat_presence for insert to authenticated with check (user_id = auth.uid());
drop policy if exists chat_presence_update_own on public.chat_presence;
create policy chat_presence_update_own on public.chat_presence for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists chat_calls_select_member on public.chat_calls;
create policy chat_calls_select_member on public.chat_calls for select to authenticated using (public.credichat_is_member(conversation_id, auth.uid()));
drop policy if exists chat_calls_insert_member on public.chat_calls;
create policy chat_calls_insert_member on public.chat_calls for insert to authenticated with check (initiated_by = auth.uid() and public.credichat_is_member(conversation_id, auth.uid()));
drop policy if exists chat_calls_update_member on public.chat_calls;
create policy chat_calls_update_member on public.chat_calls for update to authenticated using (public.credichat_is_member(conversation_id, auth.uid())) with check (public.credichat_is_member(conversation_id, auth.uid()));

drop policy if exists chat_call_participants_select_member on public.chat_call_participants;
create policy chat_call_participants_select_member on public.chat_call_participants for select to authenticated using (exists (select 1 from public.chat_calls c where c.id = call_id and public.credichat_is_member(c.conversation_id, auth.uid())));
drop policy if exists chat_call_participants_insert_own_or_initiator on public.chat_call_participants;
create policy chat_call_participants_insert_own_or_initiator on public.chat_call_participants for insert to authenticated with check (user_id = auth.uid() or exists (select 1 from public.chat_calls c where c.id = call_id and c.initiated_by = auth.uid()));
drop policy if exists chat_call_participants_update_own on public.chat_call_participants;
create policy chat_call_participants_update_own on public.chat_call_participants for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists chat_call_signals_select_recipient on public.chat_call_signals;
create policy chat_call_signals_select_recipient on public.chat_call_signals for select to authenticated using (recipient_id = auth.uid() or sender_id = auth.uid());
drop policy if exists chat_call_signals_insert_sender on public.chat_call_signals;
create policy chat_call_signals_insert_sender on public.chat_call_signals for insert to authenticated with check (sender_id = auth.uid() and exists (select 1 from public.chat_calls c where c.id = call_id and public.credichat_is_member(c.conversation_id, auth.uid())));

drop trigger if exists chat_presence_touch on public.chat_presence;
create or replace function public.chat_presence_touch()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
create trigger chat_presence_touch before update on public.chat_presence for each row execute function public.chat_presence_touch();

do $$
begin
  begin alter publication supabase_realtime add table public.chat_presence; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.chat_calls; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.chat_call_participants; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.chat_call_signals; exception when duplicate_object then null; end;
end $$;

revoke all on function public.chat_presence_touch() from public, anon, authenticated;
